### ISSUE TITLE
should the documentation be changed?

### ISSUE THREAD

**Issue by chanokin** [SpiNNakerManchester/spalloc#11]
Isn't the pip install not supported any more? shouldn't spalloc/README.rst be changed to a setup.py-based install?

**Comment by alan-stokes** [comment]
hi Gary, 

By the time the documentation is released to the end users properly (aka when the pip stuff is ready) then spalloc's pip will be updated. As most end users are expected to use the pip, this means the normal pip install would then work.

This said, the developer version page of the tool install should probably state that spalloc is a requirement, given the risk of it changing interfaces/impls between releases. Having checked, the developer version does indeed state that spalloc is a checkout dependency, therefore issue can be closed. 

As a note for alpha testers. You're expected to use the developer install, because pip hasn't been setup yet. Therefore if you have issues installing the alpha tools, please feel free to go though the developer pages and walk through step by step and see if they fail to set you up with a working version of the tools.

**Comment by dkfellows** [comment]
We also won't push things into PyPI (the repository system that pip accesses) until the release as we're still fixing some blocking bugs.
